# frozen_string_literal: true

# GENERATED by scripts/homebrew-formula.mjs in nexdrew/blitzy-cli — do not edit
# by hand; the blitzy-cli release workflow regenerates this on every release.
class BlitzyCli < Formula
  desc "Unofficial CLI for the Blitzy platform API"
  homepage "https://github.com/nexdrew/blitzy-cli"
  version "1.2.0"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.2.0/blitzy-darwin-arm64"
      sha256 "55608b32f8f274f86632bbac47a8e62c1d4d6c75e052dac42cc01d7c5987eb5f"
    end
    on_intel do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.2.0/blitzy-darwin-x64"
      sha256 "60881a73f93bbd32df49606a413356b84a4567608366cb3c89b47bca5be6c948"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.2.0/blitzy-linux-arm64"
      sha256 "0b5d2d5797f8d7642b87430780952da19331516915e4911836edd5cccadc309b"
    end
    on_intel do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.2.0/blitzy-linux-x64"
      sha256 "ecc7115abac392d4412c6c62495575a75fb88a44496d845f6ed3329810e2e382"
    end
  end

  def install
    bin.install Dir["blitzy-*"].first => "blitzy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blitzy --version")
  end
end
