# frozen_string_literal: true

# GENERATED by scripts/homebrew-formula.mjs in nexdrew/blitzy-cli — do not edit
# by hand; the blitzy-cli release workflow regenerates this on every release.
class BlitzyCli < Formula
  desc "Unofficial CLI for the Blitzy platform API"
  homepage "https://github.com/nexdrew/blitzy-cli"
  version "1.3.0"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.3.0/blitzy-darwin-arm64"
      sha256 "8e5e777520b920168b33ad14277b5f2dbc38098f3b639f510bfaadf980be0746"
    end
    on_intel do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.3.0/blitzy-darwin-x64"
      sha256 "2fa8c50b17751d4c23759e1f7e56e8a0e3850b0a0facd55cb2cca6321c312321"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.3.0/blitzy-linux-arm64"
      sha256 "3aa5362c8d8921763ca3f264c9576a8fb481c6116973d1ff15b5644a55e0afd9"
    end
    on_intel do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.3.0/blitzy-linux-x64"
      sha256 "ff759ac61f4cdc60e7a3918bab4be0f505b7717a05ceeb10bb675db4f15ad77f"
    end
  end

  def install
    bin.install Dir["blitzy-*"].first => "blitzy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blitzy --version")
  end
end
