# frozen_string_literal: true

# GENERATED by scripts/homebrew-formula.mjs in nexdrew/blitzy-cli — do not edit
# by hand; the blitzy-cli release workflow regenerates this on every release.
class BlitzyCli < Formula
  desc "Unofficial CLI for the Blitzy platform API"
  homepage "https://github.com/nexdrew/blitzy-cli"
  version "1.1.0"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.1.0/blitzy-darwin-arm64"
      sha256 "5b8c00ad5bf4bdc922e0b658c7a8bfa15ebb3921f5728a88e8aadbb357c6960e"
    end
    on_intel do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.1.0/blitzy-darwin-x64"
      sha256 "155816731554049052357540728ac6a87da8451cd29b206c1d406c3e7fce2d0a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.1.0/blitzy-linux-arm64"
      sha256 "6c6ea3ba6981a90b6f39c4a3cc11370fbf4ad2518bd4b5302f1e2464cb3c7d76"
    end
    on_intel do
      url "https://github.com/nexdrew/blitzy-cli/releases/download/v1.1.0/blitzy-linux-x64"
      sha256 "ce217090b32bd17e0f0eb7cfb14d3bd5a5345964a5a5d5f237f61417e9285ace"
    end
  end

  def install
    bin.install Dir["blitzy-*"].first => "blitzy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/blitzy --version")
  end
end
